[build]
  publish = "."  # Serve static files from root
  functions = "netlify/functions"  # Backend folder
[[redirects]]
  from = "/api/*"  # Route API calls to functions
  to = "/.netlify/functions/:splat"
  status = 200